### ISSUE TITLE
restx/classloader/CompilationManager exception

### ISSUE THREAD

**Issue by fedotxxl** [restx/restx#235] opened 2015-11-18 21:43 UTC
1. Create component `cA`, component `cB` and resource `rA`. 
2. `rA` depends on `cA`, `cB` depends on `cA`. `cB` implements `AutoStartable`
3. Resource method calls `cA` and returns value without modifications
4. Start project in dev mode

result -> unexpected behaviour.

To fix: remove `AutoStartable` dependencies. I can try to make proof project

```
2015-11-19 00:38:36,009 [qtp236304360-36 ] [          ] INFO  restx.RestxMainRouterFactory - [RESTX REQUEST] GET /app/projects/56487f50be545519b5bfc655 - per request factory created in 739.8 ms
2015-11-19 00:38:36,151 [qtp236304360-36 ] [          ] ERROR restx.StdRestxMainRouter - request raised LinkageError: loader constraint violation: loader (instance of restx/classloader/CompilationManager$11) previously initiated loading for a different type with name "my/site/site/project/MyProject"
java.lang.LinkageError: loader constraint violation: loader (instance of restx/classloader/CompilationManager$11) previously initiated loading for a different type with name "my/site/site/project/MyProject"
    at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_40]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[na:1.8.0_40]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:642) ~[na:1.8.0_40]
    at restx.classloader.HotReloadingClassLoader.defineClass(HotReloadingClassLoader.java:141) ~[restx-classloader-0.34.jar:na]
    at restx.classloader.HotReloadingClassLoader.defineClass(HotReloadingClassLoader.java:128) ~[restx-classloader-0.34.jar:na]
    at restx.classloader.HotReloadingClassLoader.defineClass(HotReloadingClassLoader.java:109) ~[restx-classloader-0.34.jar:na]
    at restx.classloader.HotReloadingClassLoader.loadClass(HotReloadingClassLoader.java:87) ~[restx-classloader-0.34.jar:na]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_40]
    at my.site.site.project.ProjectService.getInfo(ProjectService.java:52) ~[site/:na]
    at my.site.site.project.ProjectResource.getProject(ProjectResource.java:41) ~[site/:na]
    at my.site.site.project.ProjectResourceRouter$2.doRoute(ProjectResourceRouter.java:71) ~[site/:na]
    at my.site.site.project.ProjectResourceRouter$2.doRoute(ProjectResourceRouter.java:67) ~[site/:na]
    at restx.entity.StdEntityRoute.handle(StdEntityRoute.java:139) ~[restx-core-0.34.jar:na]
    at restx.RestxHandlerMatch.handle(RestxHandlerMatch.java:56) ~[restx-core-0.34.jar:na]
    at restx.ResponseCloserFilter.handle(ResponseCloserFilter.java:28) ~[restx-core-0.34.jar:na]
    at restx.RestxHandlerMatch.handle(RestxHandlerMatch.java:56) ~[restx-core-0.34.jar:na]
    at restx.CacheFilter$1.handle(CacheFilter.java:51) ~[restx-core-0.34.jar:na]
    at restx.RestxHandlerMatch.handle(RestxHandlerMatch.java:56) ~[restx-core-0.34.jar:na]
    at restx.security.RestxSessionLogFilter.handle(RestxSessionLogFilter.java:43) ~[restx-core-0.34.jar:na]
    at restx.RestxHandlerMatch.handle(RestxHandlerMatch.java:56) ~[restx-core-0.34.jar:na]
    at restx.security.RestxSessionCookieFilter.handle(RestxSessionCookieFilter.java:96) ~[restx-core-0.34.jar:na]
    at restx.RestxHandlerMatch.handle(RestxHandlerMatch.java:56) ~[restx-core-0.34.jar:na]
    at restx.stats.RestxStatsCollectionFilter.handle(RestxStatsCollectionFilter.java:39) ~[restx-stats-admin-0.34.jar:na]
    at restx.RestxHandlerMatch.handle(RestxHandlerMatch.java:56) ~[restx-core-0.34.jar:na]
    at restx.StdRestxMainRouter.route(StdRestxMainRouter.java:152) ~[restx-core-0.34.jar:na]
    at restx.RestxMainRouterFactory$PerRequestFactoryLoader.route(RestxMainRouterFactory.java:228) [restx-core-0.34.jar:na]
    at restx.RestxMainRouterFactory$RecordingMainRouter.route(RestxMainRouterFactory.java:185) [restx-core-0.34.jar:na]
    at restx.RestxMainRouterFactory$CompilationManagerRouter.route(RestxMainRouterFactory.java:337) [restx-core-0.34.jar:na]
    at restx.servlet.AbstractRestxMainRouterServlet.service(AbstractRestxMainRouterServlet.java:48) [restx-servlet-0.34.jar:na]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:770) [javax.servlet-api-3.0.1.jar:3.0.1]
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:669) [jetty-servlet-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455) [jetty-servlet-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:536) [jetty-security-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382) [jetty-servlet-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.server.Server.handle(Server.java:365) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:926) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:988) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:635) [jetty-http-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235) [jetty-http-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628) [jetty-io-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52) [jetty-io-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) [jetty-util-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) [jetty-util-8.1.8.v20121106.jar:8.1.8.v20121106]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
```

**Comment by a-peyrard** [comment] 2015-11-20 15:47
Feel free to submit your proof project, it will help us to reproduce the problem.

**Comment by fcamblor** [comment] 2017-08-22 22:05
Sounds a duplicate of #236

**Closed by fcamblor** 2017-08-22 22:05 UTC
