### ISSUE TITLE
 @Provides   public <K, V> ChronicleMap<K, V> chronicleMap(Class<K> keyClass, Class<V> valueClass) {}

### ISSUE THREAD

**Issue by Dreampie** [restx/restx#132] opened 2014-12-17 07:36 UTC
ModuleFactoryMachine error：

``` java
非法的表达式开始
```

**Comment by fcamblor** [comment] 2017-08-24 22:43
I guess this is a duplicate of #159

**Closed by fcamblor** 2017-08-24 22:43 UTC
