### ISSUE TITLE
How to get RestxResponse object in Resource?

### ISSUE THREAD

**Issue by fedotxxl** [restx/restx#183] opened 2015-03-28 15:31 UTC
I haven't found any info about following operations:
- how to set response status?
- how to add custom header?

I thought I can inject `RestxResponse` object but it doesn't work. So how can I access `RestxResponse` object in my `Resource`?

**Comment by fcamblor** [comment] 2015-03-28 22:21
Closing since seems a dupe of #101 (where you will have answers to your questions)

**Closed by fcamblor** 2015-03-28 22:21 UTC
