### ISSUE TITLE
How to serialize all GET params to single bean?

### ISSUE THREAD

**Issue by fedotxxl** [restx/restx#194] opened 2015-04-17 20:51 UTC
Hello. Is it possible to define the single bean object for all GET params? Currently I have to define list of simple params which is slightly messy than POJO style

**Comment by fcamblor** [comment] 2015-04-18 08:13
Duplicate of #146

I already started working on it (see PR #177 which is a work in progress)

**Closed** 2015-04-18 08:14 UTC
