### ISSUE TITLE
Update to Jackson 2.5.1

### ISSUE THREAD

**Issue by dadoonet** [restx/restx#174] opened 2015-03-06 10:01 UTC
[Jackson 2.5.1](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.5.1) was released a while ago.

I started to create a PR but I got a some test failures (in JSON tests) as expected messages changed.
I was able to fix some of them but not all: TBH I don't like changing what is expected in a test :)

That said, I open this issue for 2 reasons.
1st:  I'd like to make sure we don't forgot to update it at some point :)
2nd: I'd like to open a discussion about shading Jackson within RestX. This is something we are doing at elasticsearch so people can mix their Jackson versions without the need to wait for a new release.

For example, im my project if I define Jackson to be 2.5.1, RestX fails at startup as there are breaking changes between both versions.

Thoughts?

**Comment by xhanin** [comment] 2015-03-08 15:48
About upgrading to jackson 2.5, it's supposed to be backward compatible but indeed I have a some issues with tests:
- some tests of the json diff facility break because the new version of Jackson is more precise when giving location during parsing. That seems rather a good move, so I think we can change the tests expectation
- a test about handling polymorphic lists in `samplest` is failing, and this is a regression we can't afford.

I've just created a branch to keep track of these changes, but we shouldn't have to @Ignore the test in `samplest`. I will try to see how to make it work / if this is a bug in jackson.

Now about shading: I think it's a good thing for a tool like elasticsearch, where Jackson is part of the internals of the tool. Restx is a framework, and Jackson is publicly exposed: you use Jackson annotations to configure your mapping, and you can customize it also. So I don't think shading is a good idea. Note that if you really want you can get rid of Jackson version used by restx but that's cumbersome and you loose the very good integration and tests already done. But it should be possible, the mapping mechanism used to convert entities to json is done through the `JsonContentTypeModule`.

BTW, I'm curious about the error you get at startup when trying to define Jackson as 2.5.1. Besides the problem with polymorphic lists I didn't notice any problem.

**Comment by fcamblor** [comment] 2017-08-23 23:11
This issue sounds fixed by #228

**Closed by fcamblor** 2017-08-23 23:11 UTC
Labels: enhancement
