### ISSUE TITLE
Guava event bus + hot recompile = nightmare

### ISSUE THREAD

**Issue by fedotxxl** [restx/restx#232] opened 2015-11-15 22:08 UTC
Hello
How to use guava event bus with development mode? I tried to do following:
1. Mark service as `AutoStartable`
2. Subscribe it to event bus.
3. Post events to event bus

I found that event object classes are different because of `HotCompile` classLoader -> event bus doesn't work.

**Comment by a-peyrard** [comment] 2015-11-20 15:45
Indeed if you use an event bus to transfer objects between components, they have to not be reloaded. But not only the listener, the sender and the events too.
Did you tried to annotate all components and events involved with `@Cold` (`@Cold` permit to remove the class from the hot compilation) ?

**Comment by fcamblor** [comment] 2017-08-22 22:07
Sounds like a duplicate of #236

**Closed by fcamblor** 2017-08-22 22:07 UTC
